name: chess_core
description: Domain models and core logic rules for Chinese chess.
version: 1.0.0
homepage: https://github.com/fanjeffrey/chess-core
author: Jeffrey Fan <jiangzhu.fan@outlook.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:

dev_dependencies:
  effective_dart: ^1.1.0
  test: ^1.6.0
